name: Matrix Demo # The idea behind matrix is that you can run the same job with different parameters like os's/runners/library/framework versions.
on:
    push: 
        branches: [ main ]
        paths:
            - '.github/workflows/07-matrix.yml'
            - 'code/03-practice-project/'

jobs:
    build:
        continue-on-error: true #So that the job does not stop on a particular configuration if it fails.
        strategy: #Here we use the strategy keyword and then define a matrix of options.
            matrix: #This is the strategy method we chose.
                node-version: [ 12,14,16] #Self explanatory.
                operating-system: [ubuntu-latest, windows-latest, macos-latest ] #Self explanatory.
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3 # This is pre-installed on the runner we are using but then, this is a matrix demo ;)
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
              working-directory: code/03-practice-project/
            - name: Build project
              run: npm run build
              working-directory: code/03-practice-project/