name: Collecting Artifacts
on:
    push: 
        branches: [ main ]
        paths:
            - 'code/03-practice-project/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git Repo
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
              working-directory: ./code/03-practice-project/
            - name: Lint
              run: npm run lint
              working-directory: ./code/03-practice-project/
            - name: Run tests
              run: npm run test
              working-directory: ./code/03-practice-project/

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git Repo
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
              working-directory: ./code/03-practice-project/
            - name: Build project
              run: npm run build
              working-directory: ./code/03-practice-project/
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files #The name is upto us, but this is needed to reference these files in other jobs below, like deploy.
                path: | #This notes the folder where you need to store the files/artifacts.
                    dist 

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:

            - name: Deploy
              run: echo "Deploying...."