name: Events Deepdive
on:
    push: #This is an event.
        branches: [ main ] #This is an event filter.
        paths:             #This is also an event filter.
            - 'code/03-practice-project/**' #This is a filter parameter.
            - '!.github/**'
    workflow_dispatch:     #This is an event. (For manual trigger)
    pull_request:          #This is an event.
        types:             #This is an event filter.
            - opened       #This is an evet filter parameter.

jobs:
    build-test-deploy-pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git Repo
              uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm ci
              working-directory: ./code/03-practice-project/
            - name: Lint
              run: npm run lint
              working-directory: ./code/03-practice-project/
            - name: Run tests
              run: npm run test
              working-directory: ./code/03-practice-project/
            - name: Build project
              run: npm run build
              working-directory: ./code/03-practice-project/
            - name: Deploy
              run: echo "Deploying...."